# Generated by Django 6.0.3 on 2026-03-14 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
                ('editora', models.CharField(max_length=200)),
                ('ano_publicacao', models.IntegerField()),
                ('numero_paginas', models.IntegerField()),
                ('categoria', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=20)),
                ('idioma', models.CharField(max_length=50)),
                ('edicao', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
            ],
        ),
    ]
